---
# tasks file for debian-software

- name: add debian backports if on debian
  debug:
    msg: need to do this with apt_repository

- name: add debian backports and update package cache
  block:
    - name: add backports repository
      ansible.builtin.apt_repository:
        repo: 
        state: present
        filename: debian-backports
    - name: update the package cache
      ansible.builtin.apt:
        force_apt_get: yes
        update_cache: yes
  when: ansible_distribution_release in supported_releases | default([])

- name: Install basic command line tools
  become: yes
  apt:
    pkg:
      - bat
      - build-essential
      - curl
      - exa
      - git
      - htop
      - ncdu
      - ripgrep
      - tree
      - tmux
      - zsh
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install more specific software
  become: yes
  apt:
    pkg:
      - aria2
      - btop
      - detox
      - duf
      - ffmpeg
      - fd-find
      - flatpak
      - gnome-software-plugin-flatpak
      - handbrake
      - httpie
      - irssi
#      - oksh
      - neofetch
      - neovim
      - mpv
      - mupdf
      - syncthing
      - tldr
      - torbrowser-launcher
      - yadm
      - yt-dlp
    state: present
    update_cache: yes
    cache_valid_time: 3600
