---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: debian:bullseye
    command: /lib/systemd/systemd
    privileged: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    prepare: prepare.yml

verifier:
  name: ansible
