---
# tasks file for debian-software

- name: add debian backports if on debian
  debug:
    msg: need to do this

- name: Install basic command line tools
  become: yes
  apt: 
    pkg:
      - bat
      - build-essential
      - curl
      - exa
      - git
      - htop
      - ncdu
      - ripgrep
      - tree
      - tmux
      - zsh
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install more specific software
  become: yes
  apt: 
    pkg:
      - aria2
      - btop
      - detox
      - duf
      - ffmpeg
      - fd-find
      - flatpak
      - gnome-software-plugin-flatpak
      - handbrake
      - irssi
#      - oksh
      - neofetch
      - neovim
      - mpv
      - mupdf
      - syncthing
      - tldr
      - torbrowser-launcher
      - yadm
      - yt-dlp
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Setup Flathub remote for flatpak
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Add flatpak packages
  community.general.flatpak: name={{item}} state=present #method=user
  with_items:
    - ch.protonmail.protonmail-bridge
    - com.bitwarden.desktop
    - com.github.marktext.marktext
    - com.github.tchx84.Flatseal
    - com.mattermost.Desktop
    - com.spotify.client
    - com.transmissionbt.Transmission
    - io.gitlab.librewolf-community
    - org.libreoffice.LibreOffice
    - org.musicbrainz.Picard
    - org.remmina.Remmina
