---
- name: Set current OS key
  ansible.builtin.set_fact:
    current_os: "{{ ansible_os_family }}"

- name: Set package list
  ansible.builtin.set_fact:
    pkg_common: "{{ software_packages.common | default([]) }}"
    pkg_shared: "{{ software_packages.shared | default([]) }}"
    pkg_distro: "{{ software_packages.os_specific[current_os].distro_pkgs | default([]) }}"  # yamllint disable-line rule:line-length
    pkg_rust: "{{ software_packages.os_specific[current_os].rust_pkgs | default([]) }}"
    pkg_cask: "{{ software_packages.os_specific[current_os].brew_cask | default([]) }}"
  when: software_packages is defined

- name: Set up Fedora package repositories
  ansible.builtin.import_tasks: setup_fedora_repos.yml
  when: ansible_distribution == "Fedora"

- name: Install common + shared packages
  vars:
    effective_name: "{{ item.aliases[current_os] if item.aliases is defined and item.aliases[current_os] is defined else item.name }}"  # yamllint disable-line rule:line-length
  ansible.builtin.package:
    name: "{{ effective_name }}"
    state: present
  loop: "{{ pkg_common + pkg_shared }}"
  when: ansible_os_family in ['Debian', 'RedHat', 'Archlinux']

- name: Install distro-specific packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ pkg_distro }}"
  when: ansible_os_family in ['Debian', 'RedHat', 'Archlinux']

# macOS Homebrew
- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true
  when: ansible_os_family == "Darwin"

- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ item.aliases[current_os] if item.aliases is defined and item.aliases[current_os] is defined else item.name }}"  # yamllint disable-line rule:line-length
    state: present
  loop: "{{ pkg_common + pkg_shared }}"
  when: ansible_os_family == "Darwin"

- name: Install Homebrew distro packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ pkg_distro }}"
  when: ansible_os_family == "Darwin"

- name: Install Homebrew cask packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ pkg_cask }}"
  when: ansible_os_family == "Darwin"


- name: Install Rust
  ansible.builtin.import_tasks: install_rust.yml
  when: install_rust

- name: Install Firefox
  ansible.builtin.import_tasks: install_firefox.yml
  when:
    - install_firefox
    - ansible_os_family in ['Debian', 'RedHat', 'Archlinux']

- name: Install Firefox Developer Edition
  ansible.builtin.import_tasks: install_firefox_dev.yml
  when:
    - install_firefox_dev
    - ansible_os_family in ['Debian', 'RedHat', 'Archlinux']
