---
# inventory/hosts.yml
# Unified inventory for personal and work machines

# Groups:
# - personal_linux, personal_macos, personal_windows
# - work_linux, work_windows
# - linux, mac, windows
# - laptop, desktop, vm

all:
  children:
    personal_linux:
      hosts:
        indy:
          ansible_connection: local
        les:

    personal_macos:
      hosts:
        jaguar:
          ansible_connection: local
        fender:

    personal_windows:
      hosts:
        windy:
        wes:

    work_linux:
      hosts:
        ibanez:
        gibson-mgmt:

    work_windows:
      hosts:
        sg3:

    laptop:
      hosts:
        jaguar:
        les:
        wes:
        sg3:

    desktop:
      hosts:
        fender:
        indy:
        windy:
        ibanez:

    vm:
      hosts:
        gibson-mgmt:

    mac:
      hosts:
        jaguar:
        fender:

    windows:
      hosts:
        windy:
        wes:
        sg3:

    linux:
      hosts:
        indy:
        les:
        ibanez:
        gibson-mgmt:
