---
# tasks file for flatpak
- name: Install flatpak
  ansible.builtin.package:
    name: flatpak
    state: present

- name: Setup Flathub remote for flatpak
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Add flatpak packages
  community.general.flatpak: name={{ item }} state=present # method=user
  with_items:
    - ch.protonmail.protonmail-bridge
    - com.bitwarden.desktop
    - com.github.marktext.marktext
    - com.github.tchx84.Flatseal
    - com.mattermost.Desktop
    - com.spotify.client
    - com.transmissionbt.Transmission
    - io.gitlab.librewolf-community
    - org.libreoffice.LibreOffice
    - org.musicbrainz.Picard
    - org.remmina.Remmina
