---
# tasks file for flatpak
- name: Install flatpak
  ansible.builtin.package:
    name: flatpak
    state: present

- name: Setup Flathub remote for flatpak
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak apps
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ flatpak_apps | default([]) }}"
