---
# tasks file for gnome_setup

- name: Install gnome stuff for Fedora
  ansible.builtin.dnf:
    name:
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-dash-to-dock
    state: present
  when: ansible_distribution == 'Fedora'

- name: Install gnome tweaks
  ansible.builtin.package:
    name: "{{ gnome_setup_pkgs }}"
    state: present

- name: Set desktop gsettings
  ansible.builtin.command:
    cmd: "gsettings set {{ item.schema }} {{ item.key }} {{ item.value }}"
  loop: "{{ gnome_setup_desktop_settings }}"
  changed_when: false

- name: Set workspace switching keyboard shortcuts
  ansible.builtin.command:
    cmd: "gsettings set {{ item.schema }} {{ item.key }} {{ item.value }}"
  loop: "{{ gnome_setup_keyboard_shortcuts }}"
  changed_when: false
