---
# tasks file for gnome_setup

- name: Install gnome stuff for Fedora
  dnf:
    name: 
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-dash-to-dock
    state: present
  when: ansible_distribution == 'Fedora'

- name: install gnome tweaks
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ gnome_pkgs }}"

- name: Set desktop gsettings
  command: gsettings set {{ item }}
  with_items: "{{ desktop_settings }}"

- name: Set workspace switching keyboard shortcuts
  command: gsettings set {{ item }}
  with_items: "{{ keyboard_shortcuts }}"
