---
# tasks file for gnome_setup

- name: install gnome tweaks
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ gnome_pkgs }}"

- name: Set desktop gsettings
  command: gsettings set {{ item }}
  with_items: "{{ desktop_settings }}"

- name: Set workspace switching keyboard shortcuts
  command: gsettings set {{ item }}
  with_items: "{{ keyboard_shortcuts }}"
