---
# tasks file for gnome_setup

- name: Install gnome stuff for Fedora
  ansible.builtin.dnf:
    name:
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-dash-to-dock
    state: present
  when: ansible_distribution == 'Fedora'

- name: Install gnome tweaks
  ansible.builtin.package:
    name: "{{ gnome_setup_pkgs }}"
    state: present

- name: Set desktop gsettings
  community.general.gsettings:
    schema: "{{ item.schema }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    path: "{{ item.path | default(omit) }}"
  loop: "{{ gnome_setup_desktop_settings }}"

- name: Set workspace switching keyboard shortcuts
  community.general.gsettings:
    schema: "{{ item.schema }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    path: "{{ item.path | default(omit) }}"
  loop: "{{ gnome_setup_keyboard_shortcuts }}"
