---
# vars file for gnome_setup
gnome_pkgs:
  - gnome-tweaks
  
desktop_settings:
  - "org.gnome.desktop.interface enable-hot-corners true"
  - "org.gnome.desktop.interface show-battery-percentage true"
  - "org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'"
  - "org.gnome.desktop.wm.preferences mouse-button-modifier '<Alt>'"
  - "org.gnome.desktop.wm.preferences resize-with-right-button true"
  - "org.gnome.shell.window-switcher current-workspace-only false"
  - "org.gnome.shell.app-switcher current-workspace-only false"
  - "org.gnome.desktop.input-sources xkb-options ['caps:ctrl_modifier']"


    #  - [schema: "org.gnome.desktop.interface", key: "enable-hot-corners", value: "true"]
    #  - [schema: "org.gnome.desktop.interface", key: "show-battery-percentage", value: "true"]
    #  - [schema: "org.gnome.desktop.wm.preferences", key: "button-layout", value: "':minimize,maximize,close'"]
    #  - [schema: "org.gnome.desktop.wm.preferences", key: "mouse-button-modifier", value: "'<Alt>'"]
    #  - [schema: "org.gnome.desktop.wm.preferences", key: "resize-with-right-button", value: "true"]

keyboard_shortcuts:
  - "org.gnome.desktop.wm.keybindings switch-to-workspace-left \"['<Primary><Super>Left']\""
  - "org.gnome.desktop.wm.keybindings switch-to-workspace-right \"['<Primary><Super>Right']\""
  - "org.gnome.desktop.wm.keybindings move-to-workspace-left \"['<Primary><Shift><Super>Left']\""
  - "org.gnome.desktop.wm.keybindings move-to-workspace-right \"['<Primary><Shift><Super>Right']\""

# Fedora (and presumably non-Ubuntu) don't have this built in, so it won't work
#  - "org.gnome.settings-daemon.plugins.media-keys terminal \"['<Super>Return']\""
