---
# yamllint disable rule:line-length
# vars file for gnome_setup
gnome_setup_pkgs:
  - gnome-tweaks

gnome_setup_desktop_settings:
  - {schema: "org.gnome.desktop.interface", key: "enable-hot-corners", value: true}
  - {schema: "org.gnome.desktop.interface", key: "show-battery-percentage", value: true}
  - {schema: "org.gnome.desktop.wm.preferences", key: "button-layout", value: ":minimize,maximize,close"}
  - {schema: "org.gnome.desktop.wm.preferences", key: "mouse-button-modifier", value: "<Alt>"}
  - {schema: "org.gnome.desktop.wm.preferences", key: "resize-with-right-button", value: true}
  - {schema: "org.gnome.shell.window-switcher", key: "current-workspace-only", value: false}
  - {schema: "org.gnome.shell.app-switcher", key: "current-workspace-only", value: false}
  - {schema: "org.gnome.desktop.input-sources", key: "xkb-options", value: "['caps:ctrl_modifier']"}


  #  - [schema: "org.gnome.desktop.interface", key: "enable-hot-corners", value: "true"]
  #  - [schema: "org.gnome.desktop.interface", key: "show-battery-percentage", value: "true"]
  #  - [schema: "org.gnome.desktop.wm.preferences", key: "button-layout", value: "':minimize,maximize,close'"]
  #  - [schema: "org.gnome.desktop.wm.preferences", key: "mouse-button-modifier", value: "'<Alt>'"]
  #  - [schema: "org.gnome.desktop.wm.preferences", key: "resize-with-right-button", value: "true"]

gnome_setup_keyboard_shortcuts:
  - {schema: "org.gnome.desktop.wm.keybindings", key: "switch-to-workspace-left", value: "['<Primary><Super>Left']"}
  - {schema: "org.gnome.desktop.wm.keybindings", key: "switch-to-workspace-right", value: "['<Primary><Super>Right']"}
  - {schema: "org.gnome.desktop.wm.keybindings", key: "move-to-workspace-left", value: "['<Primary><Shift><Super>Left']"}
  - {schema: "org.gnome.desktop.wm.keybindings", key: "move-to-workspace-right", value: "['<Primary><Shift><Super>Right']"}
  - {schema: "org.gnome.mutter.keybindings", key: "switch-monitor", value: "<Shift><Super>p"}
  - {schema: "org.gnome.Terminal.Legacy.Keybindings", path: "/org/gnome/terminal/legacy/keybindings/", key: "next-tab", value: "<Primary>Tab"}
  - {schema: "org.gnome.Terminal.Legacy.Keybindings", path: "/org/gnome/terminal/legacy/keybindings/", key: "prev-tab", value: "<Primary><Shift>Tab"}


# Fedora (and presumably non-Ubuntu) don't have this built in, so it won't work
#  - "org.gnome.settings-daemon.plugins.media-keys terminal \"['<Super>Return']\""
