---
# yamllint disable rule:line-length
# tasks file for m3db-client
- name: Create /home/m3db directory if it doesn't exist
  ansible.builtin.file:
    path: /home/m3db
    state: directory
    mode: '0777'

- name: Install cifs packages for using samba share
  ansible.builtin.package:
    name: cifs-utils
    state: present

- name: Enable service to hopefully help cifs mount on boot
  ansible.builtin.systemd:
    name: systemd-networkd-wait-online
    enabled: true
    state: stopped

# state: present means create but don't mount. state: mounted means create if it doesn't exist and mount
- name: Add m3db to fstab (right now this messes up backslashes and must be fixed manually)
  ansible.posix.mount:
    path: /home/m3db
    src: "//ral.factor500.com/m3db"
    fstype: cifs
    opts: defaults,rw,nocase,gid=500,uid=500,file_mode=0777,dir_mode=0777,username=m3db
    state: present
