---
# tasks file for common
- name: Enable RPM Fusion free repository for Fedora
  become: true
  dnf:
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-36.noarch.rpm"
    #name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'

- name: report ansible_os_family value
  debug:
    msg: "Var ansible_os_family is set to {{ ansible_os_family }}"

- name: Set distro-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - default.yml

- name: Install common tools
  become: true
  become_user: root
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_tools }}"

- name: Install more packages
  become: true
  become_user: root
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ shared_pkgs }}"

- name: Install distro specific packages
  become: true
  become_user: root
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ distro_pkgs }}"

- name: install rust by rustup and prereqs
  import_tasks: install-rust.yml

- name: download and setup firefox-dev
  import_tasks: firefox-dev.yml

- name: download and setup firefox in opt
  import_tasks: firefox.yml
