---
# tasks file for common
- name: report ansible_os_family value
  debug:
    msg: "Var ansible_os_family is set to {{ ansible_os_family }}"

- name: Set distro-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - default.yml

- name: Install common tools
  become: true
  become_user: root
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_tools }}"

- name: Install more packages
  become: true
  become_user: root
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ shared_pkgs }}"

- name: install rust by rustup and prereqs
  import_tasks: install-rust.yml
