---
apt_packages:
  - aria2
  - bat
  - build-essential
  - curl
  - detox
  - exa
  - ffmpeg
  - flatpak
  - git
  - gnome-software-plugin-flatpak
  - htop
  - irssi
  - ncdu
  - neovim
  - ripgrep
  - tldr
  - tree
  - tmux
  - yadm
  - zsh

homebrew_packages:
  - bat
  - curl
  - exa
  - fd
  - git
  - htop
  - ncdu
  - neovim
  - ripgrep
  - tree
  - tmux
  - aria2
  - btop
  - detox
  - ffmpeg
  - git-delta
  - handbrake
  - httpie
  - irssi
  - mas
  - neofetch
  - mpv
  - yadm
  - yt-dlp
