---
# vars file for common
distro_pkgs:
  - flatpak
  - fd-find
  - torbrowser-launcher
  - yadm

rust_pkgs:
  - cmake
  - freetype2
  - fontconfig
  - pkg-config
  - make
  - libxcb
  - libxkbcommon
  - python
