---
# vars file for Debian in common
distro_pkgs:
  - flatpak
  - fd-find
  - torbrowser-launcher
  - yadm
  - build-essential

rust_pkgs:
  - cmake
  - pkg-config
  - libfreetype6-dev
  - libfontconfig1-dev
  - libxcb-xfixes0-dev
  - libxkbcommon-dev
  - python3
