---
# vars file for RedHat in common
distro_pkgs:
  - alacritty
  - flatpak
  - gcc
  - gcc-c++
  - git-delta
  - kernel-devel
  - make
  - oksh
  - tealdeer
  - torbrowser-launcher

rust_pkgs:
  - cmake
  - freetype-devel
  - fontconfig-devel
  - libxcb-devel
  - libxkbcommon-devel
  - g++
