---
name: CI

'on':
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-syntax:
    name: Lint and Syntax Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          ansible-galaxy collection install -r requirements.yml
      - name: Lint YAML
        run: yamllint .
      - name: Ansible Lint
        run: ansible-lint
      - name: Syntax check
        run: ansible-playbook playbooks/site.yml --syntax-check

  playbook-tests:
    name: Playbook Tests
    runs-on: ubuntu-latest
    needs: lint-and-syntax
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          ansible-galaxy collection install -r requirements.yml
      - name: Run test playbooks
        run: |
          ansible-playbook tests/test_all.yml --check -i inventory/hosts.yml
          ansible-playbook tests/test_personal_linux.yml --check -i inventory/hosts.yml
          ansible-playbook tests/test_work_mac.yml --check -i inventory/hosts.yml

  molecule-tests:
    name: Molecule Tests
    runs-on: ubuntu-latest
    needs: lint-and-syntax
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          ansible-galaxy collection install -r requirements.yml
      - name: Check Docker availability
        run: docker --version || echo "Docker not available"
      - name: Run molecule test
        run: |
          cd roles/software
          molecule test
